name: flutter_snake_navigationbar
description: Flutter bottom navigation bar widget with snake animation on change item.
version: 0.4.1+4

homepage: https://github.com/AllinMobile/SnakeBottomNavigationBar.git

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter